-- Create a new table to store sensitive, unredacted data.
CREATE TABLE IF NOT EXISTS secure_storage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_chunk_id BIGINT NOT NULL,
    original_text TEXT NOT NULL,
    redactions JSONB, -- To store details about what was redacted
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_file_chunk
        FOREIGN KEY(file_chunk_id)
        REFERENCES file_chunks(id)
        ON DELETE CASCADE
);

-- Add Row Level Security (RLS) to the new table.
-- By default, no one can access this table unless a policy allows it.
ALTER TABLE secure_storage ENABLE ROW LEVEL SECURITY;

-- Create an index on the foreign key for faster lookups.
CREATE INDEX IF NOT EXISTS idx_secure_storage_file_chunk_id ON secure_storage(file_chunk_id);
