[phases.setup]
nixPkgs = ["pkgs.python3"]

[phases.install]
cmds = ["python3 -m venv /opt/venv", "source /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Backend build complete - frontend should be deployed separately'"]

[start]
cmd = "source /opt/venv/bin/activate && cd /app && PYTHONPATH=/app/src uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
NIXPACKS_PYTHON_VERSION = "3.9" 