[phases.setup]
nixPkgs = ["pkgs.python3", "pkgs.python3Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Backend build complete - frontend should be deployed separately'"]

[start]
cmd = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"

[variables]
NIXPACKS_PYTHON_VERSION = "3.9" 